#!/usr/bin/env python3
"""Qwen2.5-VL + ReFindVLA LoRA inference service.

The service returns a high-level structured decision. Low-level flight
commands are generated by the local CARLA-Air controller, not by Qwen.
"""

import base64
import io
import json
import os
import tempfile
import time
from pathlib import Path
from typing import Optional, Dict, Any

import torch
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from PIL import Image as PILImage
import uvicorn

from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor
from peft import PeftModel
from qwen_vl_utils import process_vision_info

torch.backends.cuda.matmul.allow_tf32 = True
torch.set_float32_matmul_precision("high")

# Paths are configurable because the base Qwen model is not distributed in
# this repository. The LoRA adapter included with the project is used by
# default when the server is started from Code/.
CODE_ROOT = Path(__file__).resolve().parent.parent
BASE_MODEL_PATH = os.environ.get(
    "QWEN_BASE_MODEL",
    "/data/models/qwen/Qwen2.5-VL-7B-Instruct",
)
LORA_PATH = os.environ.get(
    "REFINDVLA_LORA_PATH",
    str(CODE_ROOT / "models_" / "mode_v2"),
)

# ========== 加载模型 ==========
print("=" * 60)
print("正在加载基础模型...")
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    BASE_MODEL_PATH,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

print("正在加载 LoRA...")
model = PeftModel.from_pretrained(model, LORA_PATH)
model.eval()

print("正在加载 Processor...")
processor = AutoProcessor.from_pretrained(BASE_MODEL_PATH, trust_remote_code=True)

print("=" * 60)
device_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"
memory_gb = torch.cuda.memory_allocated() / 1024**3 if torch.cuda.is_available() else 0.0
print(f"模型加载成功！设备: {device_name}")
print(f"显存占用: {memory_gb:.1f}GB")
print("=" * 60)

# ========== FastAPI 应用 ==========
app = FastAPI(title="ReFindVLA Qwen2.5-VL inference service")

class PredictRequest(BaseModel):
    image_b64: str
    user_text: str

class PredictResponse(BaseModel):
    response: str
    action: Optional[Dict[str, Any]] = None
    latency_ms: float
    timing_ms: Optional[Dict[str, float]] = None


DECISION_KEYS = {
    "phase",
    "view",
    "target_found",
    "confidence",
    "hold_seconds",
    "reason",
}


def _extract_action_from_response(response: str) -> Optional[Dict[str, Any]]:
    """Extract the current high-level ReFindVLA decision JSON.

    The old continuous-tracking action schema (vx/vy/vz/yaw_rate) is not
    accepted here because it belongs to the removed legacy tracking chain.
    """
    import re

    candidates = [response.strip()]
    match = re.search(r"\{.*\}", response, flags=re.S)
    if match:
        candidates.append(match.group(0))
    for text in candidates:
        try:
            data = json.loads(text.removeprefix("```json").removeprefix("```").removesuffix("```").strip())
        except json.JSONDecodeError:
            continue
        if not isinstance(data, dict):
            continue
        if isinstance(data.get("action"), dict):
            data = data["action"]
        if any(key in data for key in DECISION_KEYS):
            return {key: data[key] for key in DECISION_KEYS if key in data}
    return None

@app.get("/health")
async def health():
    return {
        "status": "ok",
        "model": "Qwen2.5-VL-7B + ReFindVLA LoRA",
        "device": str(next(model.parameters()).device),
        "gpu_memory_gb": torch.cuda.memory_allocated()/1024**3 if torch.cuda.is_available() else 0.0,
        "base_model_path": BASE_MODEL_PATH,
        "lora_path": LORA_PATH,
    }

@app.post("/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    t0 = time.perf_counter()
    timing: Dict[str, float] = {}

    try:
        t_decode = time.perf_counter()
        img_bytes = base64.b64decode(req.image_b64)
        img = PILImage.open(io.BytesIO(img_bytes)).convert("RGB")
        timing["decode_ms"] = (time.perf_counter() - t_decode) * 1000
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"image_decode_failed: {e}")

    tmp_path = None
    try:
        t_tmp = time.perf_counter()
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f:
            img.save(f, format="PNG")
            tmp_path = f.name
        timing["encode_tmp_ms"] = (time.perf_counter() - t_tmp) * 1000

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": tmp_path},
                    {"type": "text", "text": req.user_text},
                ],
            }
        ]

        t_prompt = time.perf_counter()
        text = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        timing["chat_template_ms"] = (time.perf_counter() - t_prompt) * 1000

        t_vision = time.perf_counter()
        vision_info = process_vision_info(messages)
        if len(vision_info) == 3:
            image_inputs, video_inputs, _ = vision_info
        else:
            image_inputs, video_inputs = vision_info
        timing["vision_extract_ms"] = (time.perf_counter() - t_vision) * 1000

        t_proc = time.perf_counter()
        inputs = processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        ).to(model.device)
        timing["processor_ms"] = (time.perf_counter() - t_proc) * 1000

        t_gen = time.perf_counter()
        with torch.inference_mode():
            generated_ids = model.generate(
                **inputs,
                max_new_tokens=64,
                do_sample=False,
                num_beams=1,
                use_cache=True,
            )
        timing["generate_ms"] = (time.perf_counter() - t_gen) * 1000

        input_len = inputs.input_ids.shape[1]
        output_ids = generated_ids[:, input_len:]
        t_out = time.perf_counter()
        response = processor.batch_decode(output_ids, skip_special_tokens=True)[0].strip()
        timing["decode_output_ms"] = (time.perf_counter() - t_out) * 1000

        action = _extract_action_from_response(response)
        latency = (time.perf_counter() - t0) * 1000

        return PredictResponse(
            response=response,
            action=action,
            latency_ms=round(latency, 1),
            timing_ms={k: round(v, 1) for k, v in timing.items()},
        )

    finally:
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

